### ISSUE TITLE
预测

### ISSUE THREAD

**Issue by lilihongjava** [Renovamen/pcalg-py#1]
我理解可以通过训练数据生成CPDAG。
那pc算法是怎么做预测，这点没明白

**Comment by Renovamen** [comment]
pc 算法是个基于统计的方法，不存在训练这个步骤。它是直接在你想预测的数据上算条件独立性之类的东西，然后删边建图，最后剩下的有向图就是你想要的预测结果。

我觉得这篇论文把 pc 算法的流程讲得挺清楚的：https://www.jmlr.org/papers/volume8/kalisch07a/kalisch07a.pdf

**Comment by Renovamen** [comment]
等等我突然意识到你的意思可能是拿贝叶斯网络做分类器该怎么预测...

贝叶斯网络可以理解为由一个有向无环图（结构，表示变量之间的依赖关系）和一个条件概率表（参数，表示变量之间的依赖程度）组成，所以要建完整的贝叶斯网络需要结构学习和参数学习。而 pc 算法只是结构学习，只能学出那个有向无环图（结构）。要预测的话还需要进行参数学习，把模型的参数学出来之后才能做预测。

贝叶斯网络的参数学习可以看看邱锡鹏老师那本《神经网络与深度学习》里概率图模型那一章：https://github.com/nndl/nndl.github.io
