### ISSUE TITLE
关于test.csv数据集的疑问

### ISSUE THREAD

**Issue by yangsongxs** [Renovamen/pcalg-py#3]
## 这里的columns为x1-x5有什么含义？
代表节点吗？一共5个节点？  

## 每一行又代表什么？  
一行代表一个样本吗？样本数为10000？  

## 每个样本里面的数字大概代表什么含义？  

非常感谢。

**Comment by Renovamen** [comment]
你好，抱歉回复晚了。

x1...x5 是 5 个节点，下面每一行是一个特征，比如第 1 列第 5 行是节点 1 的第 5 个特征的值。`test.csv` 里的特征值是我为了测试随便瞎编的，实际上这里应该用真实的特征值。

pc 算法就是在根据特征值来对节点建因果图。
